version: "3.9"
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=TailoringApp123!
    ports:
      - "1433:1433"
  api:
    build:
      context: ./backend/src/TailoringApp.API
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__Default=Server=db,1433;Database=TailoringDB;User Id=sa;Password=TailoringApp123!;TrustServerCertificate=True;MultipleActiveResultSets=True
    depends_on:
      - db
    ports:
      - "5000:5000"
  frontend:
    build:
      context: ./frontend/splitit-web
    environment:
      - VITE_API_BASE_URL=http://localhost:5000
    depends_on:
      - api
    ports:
      - "3000:3000"
